In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
y=[1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


%timeit is used to check the time in creation of list or array

In [4]:
%timeit [j**4 for j in range(1,9)]

2.32 µs ± 259 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [6]:
%timeit np.arange(1,9)**4

1.53 µs ± 64.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# creation of array 


In [17]:
x=np.array([1,2,3])
print(x)

print(x.ndim)

[1 2 3]
1


In [15]:
l=[]

for i in range(1,5):
    int_1=int(input("enter: "))
    l.append(int_1)

print(np.array(l)) 

enter: 12
enter: 13
enter: 14
enter: 15
[12 13 14 15]


In [18]:
ar_2=np.array([[1,2,3,4],[1,2,3,4]])
print(ar_2)
print(ar_2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [19]:
ar_3=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar_3)
print(ar_3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [20]:
ar_n=np.array([1,2,3,4],ndmin=10)
print(ar_n)
print(ar_n.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# array with numpy functions

In [21]:
a=np.zeros(4)
print(a)

[0. 0. 0. 0.]


In [26]:
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
b=np.ones(4)
print(b)

[1. 1. 1. 1.]


In [28]:
b=np.ones((4,5))
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [29]:
c=np.empty(4)
print(c)

[1. 1. 1. 1.]


1 isiliye aaya h kyuki empty array m previous wala data khud aa jata h 

# range

In [30]:
d=np.arange(4)
print(d)

[0 1 2 3]


# diagonal

In [31]:
e=np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
e=np.eye(3,5)
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# linspace

In [38]:
f=np.linspace(0,20,num=5)
print(f)

[ 0.  5. 10. 15. 20.]


# Random

rand() is used to generate a random value between 0 and 1

In [2]:
import numpy as np
var=np.random.rand(4)
print(var)

[0.99118626 0.47570422 0.2744213  0.77949648]


In [3]:
var1=np.random.rand(2,5)
print(var1)

[[0.33466447 0.81502677 0.6819879  0.07900515 0.29679177]
 [0.95751751 0.6335629  0.32065294 0.1978301  0.81688949]]


randn() is used to generate random numbers near the value of 0 .it can be either positive or negative

In [4]:
var2=np.random.randn(4)
print(var2)

[ 1.39787459 -0.55637886  1.06519254 -0.68082929]


ranf() range[0,1)

In [6]:
var3=np.random.ranf(4)
print(var3)

[0.37230734 0.57508549 0.91110499 0.6989913 ]


randint()  is used to generate random numbers between the specific numbers
syntax:- randit(min,max,total_values)

In [11]:
var4=np.random.randint(4,94,9)
print(var4)

[21 52 58  4  4 60 84 25 13]


# Data Types

In [14]:
var=np.array([1,2,3,4])
print("Data type: ",var.dtype)

Data type:  int32


In [15]:
var=np.array([1.0,2.3,4.4,2.2])
print("Data type: ",var.dtype)

Data type:  float64


In [16]:
var=np.array(["a","b","c"])
print("Data type: ",var.dtype)

Data type:  <U1


In [17]:
var=np.array([1,2,"a","b"])
print("Data type: ",var.dtype)

Data type:  <U11


# conversion of data types

In [19]:
var=np.array([1,2,3,4],dtype=np.int8)
print("Data type: ",var.dtype)

Data type:  int8


In [22]:
var=np.array([1,2,3,4],dtype="f")
print("Data type: ",var.dtype)
print(var)

Data type:  float32
[1. 2. 3. 4.]


In [23]:
var=np.array([1,2,3,4])
new=np.float32(var)
new_one=np.int_(var)

print("Data type: ",var.dtype)
print("Data type: ",new.dtype)
print("Data type: ",new_one.dtype)

print(var)
print(new)
print(new_one)

Data type:  int32
Data type:  float32
Data type:  int32
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [25]:
var=np.array([1,2,3,4])
new_1=var.astype(float)

print("Data type: ",var.dtype)
print("Data type: ",new_1.dtype)

print(var)
print(new_1)

Data type:  int32
Data type:  float64
[1 2 3 4]
[1. 2. 3. 4.]


# Arithmatic operations 

In [3]:
import numpy as np
var1=np.array([1,2,3,4])
var2=np.array([2,3,4,5])
varadd=var1+var2
print(varadd)

[3 5 7 9]


In [4]:
var1=np.array([1,2,3,4])
var2=np.array([2,3,4,5])
varadd=np.add(var1,var2)
print(varadd)

[3 5 7 9]


In [8]:
var1=np.array([[1,2,3,4],[4,1,2,3]])
var2=np.array([[2,3,4,5],[1,2,1,2]])
varadd=var2-var1
print(varadd)

[[ 1  1  1  1]
 [-3  1 -1 -1]]


In [6]:
var1=np.array([1,2,3,4])
var2=np.array([2,3,4,5])
varsub=var2-var1
print(varsub)

[1 1 1 1]


In [7]:
var1=np.array([1,2,3,4])
var2=np.array([2,3,4,5])
varsub=np.subtract(var2,var1)
print(varsub)

[1 1 1 1]


In [9]:
var1=np.array([[1,2,3,4],[1,1,1,1]])
var2=np.array([[2,3,4,5],[2,11,11,1]])
varsub=np.subtract(var2,var1)
print(varsub)


[[ 1  1  1  1]
 [ 1 10 10  0]]


In [10]:
var1=np.array([1,2,3,4])
var2=np.array([2,3,4,5])
varmul=var2*var1
print(varmul)

[ 2  6 12 20]


In [11]:
var1=np.array([1,2,3,4])
var2=np.array([2,3,4,5])
varmul=np.multiply(var1,var2)
print(varmul)

[ 2  6 12 20]


In [12]:
var1=np.array([[1,2,3,4],[4,3,4,6]])
var2=np.array([[2,3,4,5],[4,3,4,6]])
varmul=var2*var1
print(varmul)

[[ 2  6 12 20]
 [16  9 16 36]]


In [13]:
var1=np.array([1,2,3,4])
var2=np.array([2,3,4,5])
vardiv=np.divide(var1,var2)
print(vardiv)

[0.5        0.66666667 0.75       0.8       ]


In [17]:
#3%2=1
var1=np.array([1,2,3,4])
var2=np.array([2,3,4,5])
varmod=np.mod(var2,var1)
print(varmod)

[0 1 1 1]


In [15]:
#why 0 jabki float values bhi aa sakti h 
var1=np.array([1,2,3,4])
var2=np.array([2,3,4,5])
varreci1=np.reciprocal(var1)
varreci2=np.reciprocal(var2)
print(varreci1)
print(varreci2)

[1 0 0 0]
[0 0 0 0]


In [16]:
#1^2=1
var1=np.array([1,2,3,4])
var2=np.array([2,3,4,5])
varpow=np.power(var1,var2)
print(varpow)

[   1    8   81 1024]



# Arithmatic functions

In [13]:
import numpy as np
var=np.array([[1,2,3,4,5,6,7,8],[9,4,5,6,1,2,3,7]])
print("min :",np.min(var,axis=0))
print()
print("max :",np.max(var,axis=0))
print()
print("index no. of min :",np.argmin(var,axis=1))
print()
print("index no. of max :",np.argmax(var,axis=1))
print()
print("squareroot :",np.sqrt(var))
print()
print("value of sin :",np.sin(var))
print()
print("value of cos :",np.cos(var))
print()
print("cumulative sum :",np.cumsum(var,axis=1))

min : [1 2 3 4 1 2 3 7]

max : [9 4 5 6 5 6 7 8]

index no. of min : [0 4]

index no. of max : [7 0]

squareroot : [[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
  2.64575131 2.82842712]
 [3.         2.         2.23606798 2.44948974 1.         1.41421356
  1.73205081 2.64575131]]

value of sin : [[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
   0.6569866   0.98935825]
 [ 0.41211849 -0.7568025  -0.95892427 -0.2794155   0.84147098  0.90929743
   0.14112001  0.6569866 ]]

value of cos : [[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
   0.75390225 -0.14550003]
 [-0.91113026 -0.65364362  0.28366219  0.96017029  0.54030231 -0.41614684
  -0.9899925   0.75390225]]

cumulative sum : [[ 1  3  6 10 15 21 28 36]
 [ 9 13 18 24 25 27 30 37]]


In [14]:
import numpy as np
var=np.array([1,2,3,4,5,6,7,8])
print("min :",np.min(var))
print()
print("max :",np.max(var))
print()
print("index no. of min :",np.argmin(var))
print()
print("index no. of max :",np.argmax(var))
print()
print("squareroot :",np.sqrt(var))
print()
print("value of sin :",np.sin(var))
print()
print("value of cos :",np.cos(var))
print()
print("cumulative sum :",np.cumsum(var))

min : 1

max : 8

index no. of min : 0

index no. of max : 7

squareroot : [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712]

value of sin : [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825]

value of cos : [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003]

cumulative sum : [ 1  3  6 10 15 21 28 36]


# Shape

In [17]:
var=np.array([1,2,3,4,5,6,7])
var1=np.array([[1,2,3,4],[5,6,7,8]])
print(var.shape)
print(var1.shape)

(7,)
(2, 4)


In [21]:
#ndmin is used to give array the desired dimension
var2=np.array([1,2,3,4],ndmin=4)
print(var2)
print()
#ndim is used to know the dimension of array
print(var2.ndim)

[[[[1 2 3 4]]]]

4


# Reshape

In [24]:
var2=np.array([1,2,3,4],ndmin=4)
print(var2)
print()
print(var2.ndim)
print(var2.shape)
print()

var3=var2.reshape(2,2)
print(var3)
print(var3.ndim)
print(var3.shape)

[[[[1 2 3 4]]]]

4
(1, 1, 1, 4)

[[1 2]
 [3 4]]
2
(2, 2)



# Broadcasting array

In [8]:
import numpy as np
x=np.array([1,2,3])
print(x.shape)
print()

print(x)
print()

y=np.array([[1],[2],[3]])
print(y.shape)
print()

print(y)
print()

varadd=x+y
print(varadd)

(3,)

[1 2 3]

(3, 1)

[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


# Indexing

In [9]:
var=np.array([1,2,3])
print()

print(var.shape)
print()
print(var.ndim)
print()

print(var[1])
print(var[-2])


(3,)

1

2
2


In [11]:
var=np.array([[1,2],[3,4]])
print()

print(var.shape)
print()
print(var.ndim)
print()

print(var[0][1])
print(var[1][-1])


(2, 2)

2

2
4


In [14]:
var=np.array([[[1,2,3],[3,4,5]]])
print()

print(var.shape)
print()
print(var.ndim)
print()

print(var[0][1][2])
print(var[0][0][0])


(1, 2, 3)

3

5
1


# Slicing

In [16]:
var=np.array([1,2,3,4,5,6,7,8,9])
print(var)
print()
print("2 to 5 :",var[1:5])
print("start to 5 :",var[:5])
print("2 to end :",var[1:])
print("gap wala slicing :",var[2:6:2])

[1 2 3 4 5 6 7 8 9]

2 to 5 : [2 3 4 5]
start to 5 : [1 2 3 4 5]
2 to end : [2 3 4 5 6 7 8 9]
gap wala slicing : [3 5]


In [17]:
var=np.array([[1,2,3,4],[5,6,7,8]])
print(var)
print()
print(var[0,1:2])
print("start to 5 :",var[1,:5])
print("2 to end :",var[1,1:])
print("gap wala slicing :",var[0,2:6:2])

[[1 2 3 4]
 [5 6 7 8]]

2 to 5 : [2]
start to 5 : [5 6 7 8]
2 to end : [6 7 8]
gap wala slicing : [3]


# Iteration

In [2]:
import numpy as np
var=np.array([1,2,3,4])
print(var)
print()
for i in var:
    print(i)

[1 2 3 4]

1
2
3
4


In [3]:
import numpy as np
var=np.array([[1,2,3,4],[9,8,7,6]])
print(var)
print()
for i in var:
    for j in i:
        print(j)

[[1 2 3 4]
 [9 8 7 6]]

1
2
3
4
9
8
7
6


In [6]:
var=np.array([[1,2,3,4],[9,8,7,6]])
print(var)
print()
for i in np.nditer(var,flags=['buffered'],op_dtypes="S"):
    print(i)
    

[[1 2 3 4]
 [9 8 7 6]]

b'1'
b'2'
b'3'
b'4'
b'9'
b'8'
b'7'
b'6'


In [9]:
var=np.array([[1,2,3,4],[9,8,7,6]])
print(var)
print()
for i,d in np.ndenumerate(var):
    print(i,d)
    

[[1 2 3 4]
 [9 8 7 6]]

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 9
(1, 1) 8
(1, 2) 7
(1, 3) 6


# copy vs view

In [11]:
x=np.array([1,2,3,4])

co=x.copy()
print("x : ",x)
print("copy: ",co)
x[2]=40
print()
print("x : ",x)
print("copy: ",co)

x :  [1 2 3 4]
copy:  [1 2 3 4]

x :  [ 1  2 40  4]
copy:  [1 2 3 4]


In [12]:
x=np.array([1,2,3,4])

vi=x.view()
print("x : ",x)
print("view: ",vi)
x[2]=40
print()
print("x : ",x)
print("view: ",vi)

x :  [1 2 3 4]
view:  [1 2 3 4]

x :  [ 1  2 40  4]
view:  [ 1  2 40  4]


# join array

In [14]:
ar1=np.array([2,3,4,5])
ar2=np.array([1,6,7,8])
add=np.concatenate((ar1,ar2))
print(add)

[2 3 4 5 1 6 7 8]


In [20]:
ar1=np.array([[2,3],[4,5]])
ar2=np.array([[1,6],[7,8]])
print("ar1=",ar1)
print()
print("ar2=",ar2)
print()
add=np.concatenate((ar1,ar2),axis=0)#column
print("adding in column",add)
print()
add=np.concatenate((ar1,ar2),axis=1)#row
print("adding in row",add)

ar1= [[2 3]
 [4 5]]

ar2= [[1 6]
 [7 8]]

adding in column [[2 3]
 [4 5]
 [1 6]
 [7 8]]

adding in row [[2 3 1 6]
 [4 5 7 8]]


# stack

In [19]:
ar1=np.array([[2,3],[4,5]])
ar2=np.array([[1,6],[7,8]])
print("ar1=",ar1)
print()
print("ar2=",ar2)
print()
add=np.stack((ar1,ar2),axis=0)#column
print("adding in column",add)
print()
add=np.stack((ar1,ar2),axis=1)#row
print("adding in row",add)

ar1= [[2 3]
 [4 5]]

ar2= [[1 6]
 [7 8]]

adding in column [[[2 3]
  [4 5]]

 [[1 6]
  [7 8]]]

adding in row [[[2 3]
  [1 6]]

 [[4 5]
  [7 8]]]


# array_split

In [2]:
import numpy as np
ar=np.array([1,2,3,4,5,6])
print(ar)
print()
arsplit=np.array_split(ar,3)
print(arsplit)


[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]


In [3]:
ar=np.array([[1,2,3],[4,5,6]])
print(ar)
print()
arsplit=np.array_split(ar,3)
print(arsplit)

[[1 2 3]
 [4 5 6]]

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]


# search

In [2]:
import numpy as np
var=np.array([1,2,3,4,2,3,4,2,3,4,7])
#index        0,1,2,3,4,5,6,7,8,9,10
sarr=np.where(var==2)
print(sarr)

(array([1, 4, 7], dtype=int64),)


In [7]:
import numpy as np
var=np.array([1,2,3,4,5,6,8,9,10,11])
#index        0,1,2,3,4,5,6,7,8,9,10
sarr=np.searchsorted(var,7,side="right")
print(sarr)

6


# sort

In [10]:
var=np.array([1,4,5,6,3,2,8,10,2,11,45,9])
#index        0,1,2,3,4,5,6,7,8,9,10,11,12
sarr=np.sort(var)
print(sarr)

[ 1  2  2  3  4  5  6  8  9 10 11 45]


In [15]:
var=np.array([[1,4,5],[6,3,2],[8,10,2],[11,45,9]])
#index        0,1,2,3,4,5,6,7,8,9,10,11,12
sarr=np.sort(var)
print(sarr)
print()
sarr=np.sort(var,axis=1)
print(sarr)
print()
sarr1=np.sort(var,axis=0)
print(sarr1)

[[ 1  4  5]
 [ 2  3  6]
 [ 2  8 10]
 [ 9 11 45]]

[[ 1  4  5]
 [ 2  3  6]
 [ 2  8 10]
 [ 9 11 45]]

[[ 1  3  2]
 [ 6  4  2]
 [ 8 10  5]
 [11 45  9]]


In [16]:
var=np.array(["a","u","e","o","i"])

sarr=np.sort(var)
print(sarr)

['a' 'e' 'i' 'o' 'u']


# Filter Array

In [19]:
var=np.array(["a","u","e","o","i"])
f=[True,False,False,True,True]
sarr=var[f]
print(sarr)

['a' 'o' 'i']


# shuffle

In [22]:
var=np.array([1,2,3,4,5,6,8,9,10,11])
#index        0,1,2,3,4,5,6,7,8,9,10
np.random.shuffle(var)
print(var)

[ 9 10  4  2 11  8  5  1  3  6]


# unique

In [25]:
var=np.array([1,2,5,6,3,2,8,10,2,11,2,9])
#index        0,1,2,3,4,5,6,7,8,9,10,11,12
sarr=np.unique(var)
print(sarr)
print()
sarr1=np.unique(var,return_index=True,return_counts=True)
print(sarr1)
print()


[ 1  2  3  5  6  8  9 10 11]

(array([ 1,  2,  3,  5,  6,  8,  9, 10, 11]), array([ 0,  1,  4,  2,  3,  6, 11,  7,  9], dtype=int64), array([1, 4, 1, 1, 1, 1, 1, 1, 1], dtype=int64))



# resize

In [26]:
var=np.array([1,2,3,4,5,6])
y=np.resize(var,(2,3))
print(y)

[[1 2 3]
 [4 5 6]]


# flatten

In [28]:
var=np.array([1,2,3,4,5,6])
y=np.resize(var,(2,3))
print(y)
#order={'C','F','A','K'}
# C=row major
# F=column major
# A=means to flatten in column major if it is contiguous otherwise row major
# K=means to flatten in the order of element in the memory
arr=y.flatten(order="C")
print(arr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [30]:
var=np.array([1,2,3,4,5,6])
y=np.resize(var,(2,3))
print(y)
print()
arr=y.ravel()
print(arr)

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]


# insert

In [31]:
var=np.array([1,2,3,4])
print(var)
print()
x=np.insert(var,3,40)
print(x)

[1 2 3 4]

[ 1  2  3 40  4]


In [49]:
var=np.array([[1,2,3],[2,3,4]])
print(var)
print()
x=np.insert(var,1,40,axis=0)
print(x)
print()
x=np.insert(var,1,[4,40],axis=1)
print(x)

[[1 2 3]
 [2 3 4]]

[[ 1  2  3]
 [40 40 40]
 [ 2  3  4]]

[[ 1  4  2  3]
 [ 2 40  3  4]]


In [37]:
var=np.array([1,2,3,4])
print(var)
print()
x=np.append(var,40)
print(x)

[1 2 3 4]

[ 1  2  3  4 40]


In [72]:
var=np.array([[1,2,3],[5,4,4],[4,7,8]])
print(var)
print()
x=np.append(var,40)
print(x)


[[1 2 3]
 [5 4 4]
 [4 7 8]]

[ 1  2  3  5  4  4  4  7  8 40]


# delete

In [53]:
var=np.array([1,2,3,4])
print(var)
print()
x=np.delete(var,2)
print(x)

[1 2 3 4]

[1 2 4]


In [57]:
var=np.array([[1,2,3,4],[7,8,9,5]])
print(var)
print()
x=np.delete(var,[1],axis=0)
print(x)
print()
x=np.delete(var,[1],axis=1)
print(x)

[[1 2 3 4]
 [7 8 9 5]]

[[1 2 3 4]]

[[1 3 4]
 [7 9 5]]


# Matrix

In [59]:
var=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(var)
print()
print(var.dot(var))
print()
print(var*var)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [61]:
var=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(var)
print()
print(var.dot(var))
print()
print(var*var)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


# Matrix function

In [66]:
var=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(var)
print()
print(np.transpose(var))
print()
print(var.T)
print()
print(np.swapaxes(var,1,0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


Inverse

In [69]:
var=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(var)
print()
print(np.linalg.inv(var))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


power

In [70]:
var=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(var)
print()
print(np.linalg.matrix_power(var,0))#identity matrix
print()
print(np.linalg.matrix_power(var,2))#multiplication
print()
print(np.linalg.matrix_power(var,-1))#inverse*power

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


Determinant

In [71]:
var=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(var)
print()
print(np.linalg.det(var))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

-9.51619735392994e-16
